from typing import Literal

AssetTypes = Literal["Building", "Infrastructure", "Landscapes"]

BuildingConstructionTypes = Literal["New Construction", "Existing Asset", "Renovation/Tenant Improvement (TI)"]

InfrastructureConstructionTypes = Literal[
    "New Construction",
    "Existing Asset",
    "Major Reconstruction",
    "Minor Renovation",
    "Extension",
    "Retrofit + Extension",
]
SectorTypes = Literal[
    "Food",
    "Data/Communications",
    "Energy",
    "Industrial",
    "Land/Environmental",
    "Transportation",
    "Waste",
    "Water",
    "Other",
]

InfrastructureUseTypes = Literal[
    "Agriculture/Farm",
    "Airport",
    "Bridge",
    "Campus",
    "Dam/Levee",
    "Ecosystem Preservation",
    "Energy Distribution",
    "Energy Generation",
    "Environmental Restoration",
    "Garden",
    "Green Roof",
    "Hazardous Waste",
    "Hospitality",
    "Light Rail",
    "Maritime/Port",
    "Mixed Development",
    "Park",
    "Parking Lot",
    "Plaza",
    "Rail",
    "Recreational",
    "Reservoir",
    "Road",
    "Runway",
    "Site Development",
    "Solid Waste",
    "Stormwater",
    "Streetscape",
    "Streetcar",
    "Subway",
    "Trail",
    "Tunnel",
    "Wastewater Collection",
    "Wastewater Treatment",
    "Water Distribution",
    "Water Treatment",
    "Waterway",
    "Other: Infrastructure",
    "Other: Site",
]

UseTypes = Literal[
    "Airport",
    "Bank/Financial Institution",
    "Courthouse",
    "Data Center",
    "Education: General",
    "Education: College/University (campus-level)",
    "Education: K-12 School",
    "Food Sales: Convenience Store (w/ or w/out gas station)",
    "Food Sales:General",
    "Food Sales: Supermarket/Grocery",
    "Food Service: Fast Food",
    "Food Service: General",
    "Food Service: Restaurant/Cafeteria",
    "Health Care: Clinic",
    "Health Care: Inpatient",
    "Health Care: Medical Office",
    "Health Care: Nursing/Assisted Living",
    "Health Care: Outpatient",
    "Laboratory",
    "Lodging: General",
    "Lodging: Hotel/Motel",
    "Lodging: Residence Hall/Dormitory",
    "Retail Store",
    "Retail: Non-mall, Vehicle Dealerships, misc.",
    "Retail: Mall",
    "Office: Small (<10,000 sf/930 m2)",
    "Office: Medium (<100,000 sf/9300 m2)",
    "Office: Large (>100,000 sf/9300 m2)",
    "Parking",
    "Public Assembly: General",
    "Public Assembly: Entertainment/Culture",
    "Public Assembly: Library",
    "Public Assembly: Recreation",
    "Public Assembly: Social/Meeting",
    "Public Safety: General",
    "Public Safety: Fire/Police Station",
    "Religious Worship",
    "Residential: Mobile Homes",
    "Residential: Multifamily (2-4 units)",
    "Residential: Multifamily (5 or more units)",
    "Residential: Single-Family Attached",
    "Residential: Single-Family Detached",
    "Residential: Mid-Rise/High-Rise",
    "Service (vehicle repair/service, postal service)",
    "Warehouse: Self-storage",
    "Storage: Distribution/Shipping Center",
    "Storage: General",
    "Storage: Non-refrigerated warehouse",
    "Storage: Refrigerated warehouse",
    "Vacant",
    "Other",
]
EnergyCodes = Literal[
    "ASHRAE 189.1-2020",
    "ASHRAE 90.1-2019",
    "California Title 24 2019",
    "IECC 2021",
    "NECB 2017",
    "NECB 2020",
    "NECB 2025",
    "NYCECC",
    "Massachusetts Stretch Energy Code",
    "Seattle Energy Code (SEC)",
    "Other",
]

RiskCategories = Literal[
    "I (low risk to human life)",
    "II (all buildings and other structures)",
    "III (buildings with a substantial risk to cause economic impact and/or mass disruption)",
    "IV (buildings and other structures designated as essential facilities or the failure of which could pose a substantial hazard to the community)",
]
EarthquakeImportanceFactor = Literal["Low", "Normal", "High", "Post-Disaster"]
SeismicDesignCategory = Literal["A", "B", "C", "D", "E", "F"]
HorizontalGravitySystem = Literal[
    "Concrete: PT Framing",
    "Concrete: Non-PT Framing",
    "Concrete: Precast",
    "Concrete: Other",
    "Steel: Frame + Concrete on Metal Deck",
    "Steel: Frame + Bare Metal Deck",
    "Steel: Other",
    "Wood: Joists and Sheathing",
    "Wood: Engineered Panels",
    "Wood: Other",
    "Other",
]
VerticalGravitySystem = Literal[
    "Concrete: CIP",
    "Concrete: Precast",
    "Concrete: Other",
    "Steel: Columns",
    "Steel: Cold-Formed",
    "Steel: Other",
    "Wood: Mass Timber",
    "Wood: Light-Frame",
    "Wood: Other",
    "Masonry",
    "Other",
]
LateralSystem = Literal[
    "Concrete: Shear Walls",
    "Concrete: Moment Frames",
    "Concrete: Other",
    "Steel: Braced Frames",
    "Steel: Moment Frames",
    "Steel: Other",
    "Light Frame Shear Panels",
    "Masonry: Shear Walls",
    "Wood: Shear Panels",
    "Wood: Other",
    "Other",
]
SystemFoundationType = Literal[
    "Shallow foundation", "Deep foundation < 50' (15m)", "Deep foundation > 50' (15m)", "Other Foundation System"
]

ProjectPhase = Literal[
    "existing condition",
    "concept/planning",
    "schematic design",
    "design development",
    "construction documentation",
    "construction (administration)",
    "as-built",
    "in-use",
]
LCATool = Literal[
    "Athena IE",
    "Beacon",
    "BEAM",
    "Build Carbon Neutral",
    "CARE Tool",
    "Carbon Conscience",
    "cove.tool",
    "EC3",
    "EPIC",
    "Embodied Carbon Order of Magnitude (ECOM)",
    "eTOOL",
    "OneClick LCA",
    "Pathfinder",
    "Simapro",
    "tallyLCA",
    "Other",
]
LCAStages = Literal[
    "A0",
    "A1-A3",
    "A4",
    "A5",
    "A5.1",
    "A5.2",
    "A5.3",
    "A5.4",
    "B1",
    "B1.1",
    "B1.2",
    "B2",
    "B3",
    "B4",
    "B5",
    "B6",
    "B7",
    "B8",
    "C1",
    "C2",
    "C3",
    "C4",
    "D",
    "D1",
    "D2",
]
MaterialQtySource = Literal[
    "Extrapolation from Construction Type Land Use Area",
    "Manual Approximation",
    "BIM Model",
    "Design Estimates/ Manual Takeoff from Design Documentation",
    "Construction Estimate/Contractors Bill of Materials",
    "As-Built",
    "Other Data Source",
]

EnergyModel = Literal[
    "30 AEDG AEDG",
    "50 AERG AEDG",
    "Autodesk Insight",
    "BE Opt",
    "CBECC (Title 24 Compliance Tool)",
    "CBECC-Res (Title 24 Compliance Tool)",
    "Energos (Vectorworks Plug-In)",
    "EPIC Tool",
    "ClimateStudio",
    "Cove.tool",
    "DOE - 2.1E Energy Pro",
    "DOE - 2.1E VisualDOE",
    "EnergyGauge Summit - DOE -2.1E",
    "DOE- 2.2",
    "DOE -2.2 eQuest",
    "DOE - 2.2 GreenBuildingStudio",
    "DOE - 2.2 Other",
    "Energy Gauge Summit, DOE 2.2E",
    "EnergyPlus AECOSim",
    "EnergyPlus DesignBuilder",
    "EnergyPlus Ladybug Tools",
    "EnergyPlus OpenStudio",
    "EnergyPlus Simergy",
    "EnergyPlus Other",
    "HAP",
    "HEED",
    "HOT2000",
    "Home Energy Saver",
    "IES - Virtual Environment",
    "Modelica",
    "NEO Net Energy Optimizer",
    "Passive House Planning Package (PHPP)",
    "PlanITImpact",
    "REM Rate",
    "Sefaira",
    "SPEED",
    "TRACE 3D+",
    "TRACE 700",
    "TRNSYS",
    "URBANopt",
    "WUFI Passive",
    "Other: String",
    "Other International: String",
]
GWPEnergySource = Literal["20 year", "100 year", "Other"]
ElectricitySource = Literal[
    "Imported from a utility",
    "On-site electricity generation",
    "Direct-wired from dedicated offsite source",
    "Other",
]
BiogenicCarbonAccounting = Literal["0/0", "-1/+1", "Dynamic LCA", "Ton-Year Accounting or Discounting Method"]
BiogenicCertification = Literal["Forest Stewardship Council (FSC)", "Sustainable Forestry Initiative (SFI)", "Other"]
SubstructureScope = Literal[
    "Foundations",
    "Subgrade Enclosures",
    "Slabs-On-Grade",
    "Water and Gas Mitigation",
    "Substructure Related Activities",
    "Other",
]
ShellSuperstructureScope = Literal[
    "Floor Construction, Roof Construction", "Stairs", "Frame: Columns, Beams, Load-Bearing Walls", "Balconies", "Other"
]
ShellExteriorScope = Literal[
    "Exterior Wall",
    "Exterior Windows",
    "Exterior Doors and Grilles",
    "Exterior Louvers and Vents",
    "Exterior Wall Appurtenances",
    "Exterior Wall Specialties",
    "Roofing",
    "Roofing Appurtenances",
    "Traffic Bearing Horizontal Enclosures",
    "Horizontal Openings",
    "Overhead Exterior Enclosures",
    "Other",
]
InteriorConstructionScope = Literal[
    "Interior Partitions",
    "Interior Windows",
    "Interior Doors",
    "Interior Grilles and Gates",
    " Raised Floor Construction",
    "Suspended Ceiling Construction",
    "Suspended Ceiling Construction",
    "Other",
]
InteriorFinishesScope = Literal[
    "Wall Finishes", "Interior Fabrications", "Flooring", "Stair Finishes", "Ceiling Finishes", "Other"
]
ServicesMechanicalScope = Literal[
    "Ducts and Pipes and Their Insulation",
    "Mechanical Equipment: Chillers",
    "Cooling Towers",
    "Air Handlers",
    "Heat Pumps",
    "Boilers",
    "Chilled Beams",
    "VRF Systems",
    "VAVs",
    "Heat Exchangers",
    "Air Conditioners" "Other",
]
ServicesElectricalScope = Literal[
    "Light Fixtures",
    "Power Supply And Distribution",
    "Power Management Systems Batteries",
    "Power Management Systems: Uninterrupted Power Supplies",
    "Power Management Systems: Switchgears",
    "Power Management Systems: Transformers",
    "Power Generation Systems",
    "Other",
]
ServicesPlumbingScope = Literal[
    "Pipes Servicing Equipment And Their Insulation",
    "Plumbing Fixtures And Plumbing And Fire Protection Equipment",
    "Other",
]
SiteworkScope = Literal[
    "Site Preparations",
    "Site Improvements",
    "Liquid and Gas Site Utilities",
    "Electrical Site Improvements",
    "Communications",
    "Misc. Site Construction",
    "Other",
]
EquipmentScope = Literal[
    "Vehicle and Pedestrian Equipment",
    "Commercial Equipment",
    "Institutional Equipment",
    "Residential Equipment",
    "Entertainment and Recreational Equipment",
    "Other",
]
FurnishingScope = Literal["Fixed Furnishings", "Movable Furnishings", "Other"]

Certifications = Literal[
    "LEED v4.0 Certified",
    "LEED v4.0 Silver",
    "LEED v4.0 Gold",
    "LEED v4.0 Platinum",
    "LEED v4.1 Certified",
    "LEED v4.1 Silver",
    "LEED v4.1 Gold",
    "LEED v4.1 Platinum",
    "Envision",
    "BREEAM",
    "ILFI Zero Carbon 1.0",
    "ILFI LBC 3.1",
    "ILFI LBC 4.0",
    "ILFI Zero Energy",
    "Green Globes",
    "SE2050",
    "AIA DDx",
    "MEP 2040",
    "Contractor's Commitment",
    "Climate Positive",
    "SE2050, UK BECD Database",
    "CLF WBLCA v2 Benchmarking Study",
    "Other",
]
OwnerType = Literal[
    "Government - Federal",
    "Government - State/Province",
    "Government - Local",
    "Corporate",
    "Higher-Education",
    "Non-Profit",
    "Public-Private Partnership",
    "Investor-Developer",
    "Other",
]

ProjectStatus = Literal["Active", "On Hold", "Complete", "Cancelled"]

ProjectSurroundings = Literal["Urban", "Suburban", "Rural"]
DevelopmentSite = Literal["Greenfield", "Brownfield", "Other"]
HistoricValue = Literal["Yes", "No", "Partial"]
IBCConstructionType = Literal[
    "Type I-A",
    "Type I-B",
    "Type II-A",
    "Type II-B",
    "Type III-A",
    "Type III-B",
    "Type IV-A",
    "Type IV-B",
    "Type IV-C",
    "Type IV-HT",
    "Type V-A",
    "Type V-B",
]

SystemPodium = Literal[
    "Not a podium building", "Primary system defined above is on a podium", "Primary system defined above is a podium"
]
RefrigerantTypes = Literal[
    "R-123",
    "R-1233zd",
    "R-514A",
    "R-134A",
    "R-513A",
    "R-515B",
    "R-1234ze",
    "R-22",
    "R-410A",
    "R-466A",
    "R-452B",
    "R-454B",
    "R-32",
    "Other",
]
ClimateZones = Literal[
    "0",
    "0A",
    "0B",
    "1",
    "1A",
    "1B",
    "2",
    "2A",
    "2B",
    "3",
    "3A",
    "3B",
    "3C",
    "4",
    "4A",
    "4B",
    "4C",
    "5",
    "5A",
    "5B",
    "5C",
    "6",
    "6A",
    "6B",
    "7",
    "7A",
    "7B",
    "8",
    "8A",
    "8B",
]

CurrencyCodes = Literal[
    "AED",
    "AFN",
    "ALL",
    "AMD",
    "ANG",
    "AOA",
    "ARS",
    "AUD",
    "AWG",
    "AZN",
    "BAM",
    "BBD",
    "BDT",
    "BGN",
    "BHD",
    "BIF",
    "BMD",
    "BND",
    "BOB",
    "BRL",
    "BSD",
    "BTN",
    "BWP",
    "BYN",
    "BZD",
    "CAD",
    "CDF",
    "CHF",
    "CLP",
    "CNY",
    "COP",
    "CRC",
    "CUP",
    "CVE",
    "CZK",
    "DJF",
    "DKK",
    "DOP",
    "DZD",
    "EGP",
    "ERN",
    "ETB",
    "EUR",
    "FJD",
    "FKP",
    "GBP",
    "GEL",
    "GGP",
    "GHS",
    "GIP",
    "GMD",
    "GNF",
    "GTQ",
    "GYD",
    "HKD",
    "HNL",
    "HRK",
    "HTG",
    "HUF",
    "IDR",
    "IMP",
    "INR",
    "IQD",
    "IRR",
    "ISK",
    "JEP",
    "JMD",
    "JOD",
    "JPY",
    "KES",
    "KGS",
    "KHR",
    "KMF",
    "KPW",
    "KRW",
    "KWD",
    "KYD",
    "KZT",
    "LAK",
    "LBP",
    "LKR",
    "LRD",
    "LSL",
    "LYD",
    "MAD",
    "MDL",
    "MGA",
    "MKD",
    "MMK",
    "MNT",
    "MOP",
    "MRU",
    "MUR",
    "MVR",
    "MWK",
    "MXN",
    "MYR",
    "MZN",
    "NAD",
    "NGN",
    "NIO",
    "NOK",
    "NPR",
    "NZD",
    "OMR",
    "PAB",
    "PEN",
    "PGK",
    "PHP",
    "PKR",
    "PLN",
    "PYG",
    "QAR",
    "RON",
    "RSD",
    "RUB",
    "RWF",
    "SAR",
    "SBD",
    "SCR",
    "SDG",
    "SEK",
    "SGD",
    "SHP",
    "SLL",
    "SOS",
    "SRD",
    "SSP",
    "STN",
    "SVC",
    "SYP",
    "SZL",
    "THB",
    "TJS",
    "TMT",
    "TND",
    "TOP",
    "TRY",
    "TTD",
    "TWD",
    "TZS",
    "UAH",
    "UGX",
    "USD",
    "UYU",
    "UZS",
    "VEF",
    "VND",
    "VUV",
    "WST",
    "XAF",
    "XAG",
    "XAU",
    "XCD",
    "XDR",
    "XOF",
    "XPF",
    "YER",
    "ZAR",
    "ZMW",
    "ZWL",
]

ProjectPhaseReporting = Literal[
    "Existing Condition",
    "Concept/Planning",
    "Schematic Design",
    "Design Development",
    "Construction Documentation",
    "Construction (Administration)",
    "As-Built",
]